<a href="https://colab.research.google.com/github/granthprofessional/python-numpy-.ipynb/blob/main/array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[8]

np.int64(19)

In [6]:
arr[1:7] # array print are 1 to 7 digits, using of slicing

array([12, 13, 14, 15, 16, 17])

In [7]:
arr[:7] # array print are 0 to 7 digits

array([11, 12, 13, 14, 15, 16, 17])

In [8]:
arr[:] # array print are 0 to 10 values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr_slice = arr[3::2] # 2colon = output m 1 la gap ayega, 14,16,18,20
arr_slice

array([14, 16, 18, 20])

In [10]:
arr[4] #15

np.int64(15)

*numpy indexing and slicing of matrix😍*

In [11]:
arr = np.arange(1,31).reshape(6,5) # 6raws,5coloms
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
arr[2]

array([11, 12, 13, 14, 15])

In [19]:
arr[4]

array([21, 22, 23, 24, 25])

In [22]:
arr[0,2]

np.int64(3)

In [24]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [35]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [37]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [38]:
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

**BOOLEAN INDEXING**

In [41]:
arr = np.arange(11,21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [47]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])